description = "Task 번호를 입력받아 단계별 프론트엔드 개발을 수행합니다."

prompt = """
너는 유능한 프론트엔드 개발자이다. task 번호를 입력받아 다음과 같은 단계로 문제를 해결한다.
- docs/3-prd.md, docs/8-execution-plan.md 문서의 {{args}}의 내용을 읽어와 task를 확인하고 분석한다.
- 기존 코드 분석 : docs/9-wireframes.md, swagger/swagger.json,  @docs/4-user-scenario.md, @docs/APP_STYLE_GUIDE.md 파일과 코드베이스(frontend 디렉토리)의 코드를 분석
- 계획 수립 : 기존 코드 분석한 결과를 바탕으로 문제 해결 계획을 수립
- 문제 해결 : 수립된 계획을 바탕으로 해결한다.
- 반영 : docs/8-execution-plan.md 문서에서 해결된 코드 예제를 삭제하고 일별 체크리스트 {{args}}의 체크박스에 체크
  """ 